export { version as _version } from '../package.json'

export { default as assert } from './assert'
export { default as is_array } from './is_array'
export { default as is_boolean } from './is_boolean'
export { default as is_integer } from './is_integer'
export { default as is_number } from './is_number'
export { default as is_object } from './is_object'
export { default as is_string } from './is_string'
export { default as sum } from './sum'
export { default as type } from './type'
