if (typeof process !== 'undefined') {
  require('source-map-support').install()
}

export * from './aggregate'
export * from './array'
export * from './assert'
export * from './clone'
export * from './equal'
export * from './extend'
export * from './is_array'
export * from './is_boolean'
export * from './is_integer'
export * from './is_number'
export * from './is_object'
export * from './is_string'
export * from './is_table'
export * from './filter'
export * from './length'
export * from './max'
export * from './mean'
export * from './min'
export * from './select'
export * from './sum'
export * from './table'
export * from './t_test'
export * from './test'
export * from './test_equal'
export * from './type'
